export const RESPONSES = {
    SUCCESS: 200,
    CREATED: 201,
    ACCEPTED: 202,
    NOCONTENT: 204,
    BADREQUEST: 400,
    UN_AUTHORIZED: 401,
    INVALID_REQ: 422,
    FORBIDDEN: 403,
    NOTFOUND: 404,
    TIMEOUT: 408,
    TOOMANYREQ: 429,
    INTERNALSERVER: 500,
    BADGATEWAYS: 502,
    SERVICEUNAVILABLE: 503,
    GATEWAYTIMEOUT: 504,
  };
  export const RES_MSG = {
    NO_DATA: "No data found",
    PASSWORD_MISMATCHED: "Password Missmatched",
    SAME_PASSWORD: "New password can not be same as old password",
    CHECK_CREDENTIALS: "Check Your Email And Password",
    USER_NOT_FOUND: "User not found, Please register yourself first",
    WRONG_PASSWORD: "Invalid email/password Entered",
    BADREQUEST: "Bad Request",
    INTERNAL_SERVER_ERROR: "Internal Server Error",
    SUCCESS: "Success",
    REGISTER_SUCCESS: "Registered successfully",
    LOGIN_SUCCESS: "Logged in successfully",
    REGISTER_DUPLICACY: "Email alredy used",
    INVALID_OLD_PASSWORD: "Invalid Old Password",
    AUDITOR_NOT_FOUND: "Auditor Email Not Registered",
    BID_NOT_POSSIBLE: "Bid is no longer avaiable for this post",
    POSTER_NOT_FOUND:"Audit Poster Email missmatched",
    UN_AUTHORIZED: "Invalid/Unauthorised Access",
    TFA_SUCCESS: "Token verified successfully",
    TFA_FAIL: "Token verified FAILED",
    POST_ID_MISMATCHED: "Post ID mismatched with given Email Address",
    POST_NOT_FOUND: "Post not found"
  };
  